#!/usr/bin/env python3
"""
Build README.md (navigation index) and cheatsheet.md (consolidated review file)
for the reorganized interview vault.

The cheatsheet inlines the highest-signal sections (Java, microservices,
networking, behavioral) and links out to the larger ones (AWS, work, personal).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Sections we INLINE into the cheatsheet (paste full content for night-before review).
INLINE_SECTIONS = {
    "01-java",
    "02-microservices",
    "03-medium-series",
    "04-networking",
    "08-behavioral",
}

SECTION_TITLES = {
    "01-java": "Java — Core, Concurrency, JVM, Collections",
    "02-microservices": "Spring Boot & Microservices",
    "03-medium-series": "Medium Article Series (Shivam's curated collections)",
    "04-networking": "Networking",
    "05-aws-cloud-practitioner": "AWS Cloud Practitioner",
    "06-aws-developer-associate": "AWS Developer Associate (DVA-C02)",
    "07-devops": "DevOps & Cloud",
    "08-behavioral": "Behavioral & Self-Introduction",
    "09-references": "References, Links & Reading List",
    "10-work": "Work Notes (Elsevier / CDM / Semarchy / etc.)",
    "11-personal": "Personal (Journal, Tasks, etc.)",
    "99-uncategorized": "Uncategorized",
}


def slugify(s: str) -> str:
    s = s.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s


def collect_files(section_dir: Path) -> list[Path]:
    """All markdown files under a section, sorted."""
    return sorted(p for p in section_dir.rglob("*.md") if p.is_file())


def title_of(md_path: Path) -> str:
    """First H1 heading if present, else filename."""
    try:
        for line in md_path.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    except Exception:
        pass
    return md_path.stem.replace("-", " ").title()


def build_readme(vault: Path) -> str:
    out: list[str] = []
    out.append("# Senior Java Developer — Interview Prep Vault")
    out.append("")
    out.append(
        "Curated notes from years of Notion collections — Java, Spring Boot, "
        "microservices, AWS, system design, behavioral. Auto-organized from a "
        "Notion export, deduplicated, hash-stripped, kebab-cased."
    )
    out.append("")
    out.append("## How to use this vault")
    out.append("")
    out.append("- **Daily review** — open `cheatsheet.md` for inlined Java/Microservices/Networking/Behavioral.")
    out.append("- **Deep dive** — open any section below to read full notes.")
    out.append("- **Search** — `grep -ri 'volatile' .` from the repo root finds every mention.")
    out.append("- **Editor** — works in VS Code, Obsidian (point its vault at this folder), or rendered on GitHub Pages.")
    out.append("")
    out.append("## Sections")
    out.append("")

    for section in sorted(vault.iterdir()):
        if not section.is_dir():
            continue
        name = section.name
        title = SECTION_TITLES.get(name, name)
        md_files = collect_files(section)
        png_count = sum(1 for _ in section.rglob("*.png"))
        if not md_files and png_count == 0:
            continue
        out.append(f"### [{title}](./{name}/)")
        out.append("")
        out.append(f"_{len(md_files)} notes · {png_count} images_")
        out.append("")
        # Subsection breakdown if section has subfolders
        subfolders = sorted([p for p in section.iterdir() if p.is_dir()])
        if subfolders:
            for sub in subfolders:
                sub_md = collect_files(sub)
                if not sub_md:
                    continue
                out.append(f"- [{sub.name}](./{name}/{sub.name}/) — {len(sub_md)} notes")
            out.append("")
        else:
            for md in md_files[:10]:
                rel = md.relative_to(vault).as_posix()
                out.append(f"- [{title_of(md)}](./{rel})")
            if len(md_files) > 10:
                out.append(f"- _…and {len(md_files) - 10} more_")
            out.append("")
    out.append("---")
    out.append("")
    out.append("**Stats**")
    out.append("")
    all_md = list(vault.rglob("*.md"))
    all_png = list(vault.rglob("*.png"))
    all_csv = list(vault.rglob("*.csv"))
    word_count = sum(
        len(p.read_text(encoding="utf-8", errors="replace").split())
        for p in all_md
    )
    out.append(f"- {len(all_md)} markdown notes")
    out.append(f"- {len(all_csv)} database CSVs (also rendered as `.md` tables)")
    out.append(f"- {len(all_png)} images")
    out.append(f"- ~{word_count:,} words total")
    out.append("")
    out.append("Generated by `scripts/build_index.py`.")
    return "\n".join(out) + "\n"


def build_cheatsheet(vault: Path) -> str:
    out: list[str] = []
    out.append("# Cheatsheet — Night-Before Interview Review")
    out.append("")
    out.append(
        "Inlined: Java, Spring Boot & Microservices, Networking, Behavioral. "
        "Use Ctrl-F. For AWS / DevOps / work content, see the section folders directly."
    )
    out.append("")
    out.append("## Table of contents")
    out.append("")

    # First pass — TOC
    for section in sorted(vault.iterdir()):
        if not section.is_dir() or section.name not in INLINE_SECTIONS:
            continue
        title = SECTION_TITLES.get(section.name, section.name)
        out.append(f"- [{title}](#{slugify(title)})")
        for md in collect_files(section):
            t = title_of(md)
            anchor = slugify(f"{section.name}-{md.stem}-{t}")
            out.append(f"  - [{t}](#{anchor})")
    out.append("")
    out.append("---")
    out.append("")

    # Second pass — content
    for section in sorted(vault.iterdir()):
        if not section.is_dir() or section.name not in INLINE_SECTIONS:
            continue
        title = SECTION_TITLES.get(section.name, section.name)
        out.append(f"## {title}")
        out.append("")
        for md in collect_files(section):
            t = title_of(md)
            anchor_id = slugify(f"{section.name}-{md.stem}-{t}")
            out.append(f"<a id=\"{anchor_id}\"></a>")
            out.append(f"### {t}")
            out.append("")
            out.append(f"_Source: `{md.relative_to(vault).as_posix()}`_")
            out.append("")
            body = md.read_text(encoding="utf-8", errors="replace")
            # Strip the file's own H1 since we just printed a section header
            body = re.sub(r"^#\s+.*\n", "", body, count=1)
            # Downshift all remaining headings by 2 levels so they nest under ###
            body = re.sub(r"^(#{1,4})\s", lambda m: ("#" * min(len(m.group(1)) + 2, 6)) + " ", body, flags=re.MULTILINE)
            out.append(body.strip())
            out.append("")
            out.append("---")
            out.append("")
    return "\n".join(out) + "\n"


def main():
    vault = Path(sys.argv[1] if len(sys.argv) > 1 else "vault")
    readme = vault / "README.md"
    cheatsheet = vault / "cheatsheet.md"
    readme.write_text(build_readme(vault), encoding="utf-8")
    cheatsheet.write_text(build_cheatsheet(vault), encoding="utf-8")
    print(f"wrote {readme} ({readme.stat().st_size} bytes)")
    print(f"wrote {cheatsheet} ({cheatsheet.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
